CREATE TYPE "ProjectOrgChartAnchor" AS ENUM (
  'TOP_LEFT', 'TOP_CENTER', 'TOP_RIGHT',
  'RIGHT_TOP', 'RIGHT_CENTER', 'RIGHT_BOTTOM',
  'BOTTOM_RIGHT', 'BOTTOM_CENTER', 'BOTTOM_LEFT',
  'LEFT_BOTTOM', 'LEFT_CENTER', 'LEFT_TOP'
);

ALTER TABLE "ProjectOrgChartNode"
ADD COLUMN "photoUrl" TEXT,
ADD COLUMN "parentAnchor" "ProjectOrgChartAnchor" NOT NULL DEFAULT 'BOTTOM_CENTER',
ADD COLUMN "childAnchor" "ProjectOrgChartAnchor" NOT NULL DEFAULT 'TOP_CENTER';
