ALTER TYPE "ProjectStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';
ALTER TYPE "ApprovalStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';

ALTER TABLE "Project"
ADD COLUMN IF NOT EXISTS "cancelledAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "cancelledById" TEXT,
ADD COLUMN IF NOT EXISTS "cancellationReason" TEXT;
